services:
  postgres:
    image: postgres:16
    container_name: inventory-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - inventory-net
    ports:
      - "5432:5432"
    volumes:
      - inventory_pgdata:/var/lib/postgresql/data

  dotnet:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Host=postgres;Port=5432;Database=inventorydb;Username=postgres;Password=postgres"
    ports:
      - "8080:8080"
    networks:
      - inventory-net

networks:
  inventory-net:

volumes:
  inventory_pgdata:
